<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Page Achievements</name>
   <tag></tag>
   <elementGuidId>f6e8f24e-b73a-4887-bc4e-3ff35ae9787a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='achivement']/div[2]/div/ul/li/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.page-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;1(current)&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b4e343b0-5827-4eec-a1fe-d8692e762c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-link</value>
      <webElementGuid>1a698e60-6988-454e-8b27-36a27904dff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>75f0e6b1-6eae-485c-84bf-099ac2cd2959</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;achivement&quot;)/div[@class=&quot;justify-content-center text-center&quot;]/div[1]/ul[@class=&quot;float-right pagination-news pagination&quot;]/li[@class=&quot;page-item active&quot;]/span[@class=&quot;page-link&quot;]</value>
      <webElementGuid>dd2bc77e-b8eb-40ef-bad5-643f099b7e83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='achivement']/div[2]/div/ul/li/span</value>
      <webElementGuid>ead02822-78d4-405e-ba67-1b6128cdc202</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia Human Capital Awards 2024'])[1]/following::span[1]</value>
      <webElementGuid>1bfab0d7-19d3-453f-ab4f-2b267cda68ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia Sharia and Halal Top Brand Awards 2024'])[1]/following::span[1]</value>
      <webElementGuid>09599b76-6e46-41ba-9a80-ea77672b940c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Established'])[1]/preceding::span[6]</value>
      <webElementGuid>7f01014c-1581-444e-a81a-444d86a162fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>1777cb49-2d37-4e62-8472-602333bb0c03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/span</value>
      <webElementGuid>e958f2d7-1e3b-465b-9f4e-023d39904683</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '1(current)' or . = '1(current)')]</value>
      <webElementGuid>ee78d2f6-23bd-4b21-b0e6-aac105bad995</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
