<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>filter_Years</name>
   <tag></tag>
   <elementGuidId>77d14520-952f-492b-bca8-97fee0b517bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='achivement']/div/div[2]/form/div/div/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.form-check-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;2024&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>dadd1d50-0143-48ff-98bc-30555169fe28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>formCheckboxFilter</value>
      <webElementGuid>d3ea3e0d-5633-4680-98e2-9ab89091b594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label</value>
      <webElementGuid>77c39002-433a-45f0-addd-430349164b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2024</value>
      <webElementGuid>6d39bba3-4220-4974-b872-8ce731eaaeab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;achivement&quot;)/div[@class=&quot;d-flex justify-content-start&quot;]/div[@class=&quot;card-filter  card&quot;]/form[@class=&quot;txt-boards-desc&quot;]/div[@class=&quot;mb-3 form-group&quot;]/div[@class=&quot;mb-2 txt-boards-desc form-check&quot;]/label[@class=&quot;form-check-label&quot;]</value>
      <webElementGuid>3fb73976-270a-425d-b52a-5f56c386511f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='achivement']/div/div[2]/form/div/div/label</value>
      <webElementGuid>d127b645-9eaf-4688-8daf-d3554adae4e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Years'])[1]/following::label[1]</value>
      <webElementGuid>2eed17f1-7cad-4b81-a860-6277cbeac349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read Less &lt;&lt;&lt;'])[3]/following::label[1]</value>
      <webElementGuid>bd4fb467-6f9e-4aa0-8879-bfa306a33cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indonesia Best Multifinance Awards 2024'])[1]/preceding::label[5]</value>
      <webElementGuid>ff2e7860-9775-4c55-a1ef-55fd9d116abc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Infobank 20th Multifinance Awards 2024'])[1]/preceding::label[5]</value>
      <webElementGuid>cf472de1-58d4-45fa-bd6c-8c5c771c7659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='2024']/parent::*</value>
      <webElementGuid>45a1ebf3-29a5-4f84-96ff-afc05d9049bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
      <webElementGuid>cdb1c097-1eeb-4ec1-9f09-f4a3d0f41181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '2024' or . = '2024')]</value>
      <webElementGuid>745332db-1c25-458d-9578-411450c683c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
