<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Building</name>
   <tag></tag>
   <elementGuidId>b3e655c7-433e-4550-a4b3-09ea7243356b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/main/div[2]/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.font-weight-bold.pt-4.pb-5.col-lg-4 > div > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.font-weight-bold > div > img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>00214e22-92b5-46ee-a6bd-2b8f7f0ab5b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>cb388979-5cc7-40a5-b2ab-a48911afc567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>456024b2-aff2-45cf-ad61-3768c04498bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>9c5f32fa-0934-4ce1-9b56-74e55eb1f3e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>58adaa84-f95c-4f52-9e0e-7b55a2a80950</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>1a3492ad-749a-4737-a199-2375f3c3cfd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fbaf_plaza_fq.webp&amp;w=640&amp;q=75 1x, /_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fbaf_plaza_fq.webp&amp;w=828&amp;q=75 2x</value>
      <webElementGuid>04be5f12-a016-41bc-a3f8-c223676f3492</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fbaf_plaza_fq.webp&amp;w=828&amp;q=75</value>
      <webElementGuid>a39af4dc-cd06-4fa5-bd04-e81a726de591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__className_4df22e&quot;]/main[@class=&quot;layout&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;font-weight-bold pt-4 pb-5 col-lg-4&quot;]/div[1]/img[1]</value>
      <webElementGuid>1bd34aad-0c17-4ec8-aaba-8e260fd8d459</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[2]/div/div/img</value>
      <webElementGuid>1f29d64d-ce5a-411c-a6e3-9a60e473c744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>e97973c6-e004-45f4-8bc8-037257df1640</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fbaf_plaza_fq.webp&amp;w=828&amp;q=75']</value>
      <webElementGuid>3503a7f8-67a9-4371-bac5-4d2f2fe99ba9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
