<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Milestone BAF</name>
   <tag></tag>
   <elementGuidId>b6bfa5c4-8b2b-4139-aade-90f8c6716e07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='about']/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;MilestoneBaf2023EN&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>393da204-30db-4060-a6db-82dc72bcf14f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>MilestoneBaf2023EN</value>
      <webElementGuid>55a3b76f-f106-4c43-9a4d-18b9c103ff0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>d0bbdb6d-d0c0-454c-8213-4061ebdf7860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>9da5b9f9-78e7-41bc-9a91-cb430d534447</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>08ed0d47-d024-40b5-a682-d3e93cb2d142</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>ab163a5d-9491-465b-8802-38311a5b9eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>41a40795-b086-49d1-9874-3e2d538dc63a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fstatic%2Fimages%2Fimage%2FMilestoneBAF2023_EN.jpg&amp;w=640&amp;q=75 640w, /_next/image?url=%2Fstatic%2Fimages%2Fimage%2FMilestoneBAF2023_EN.jpg&amp;w=750&amp;q=75 750w, /_next/image?url=%2Fstatic%2Fimages%2Fimage%2FMilestoneBAF2023_EN.jpg&amp;w=828&amp;q=75 828w, /_next/image?url=%2Fstatic%2Fimages%2Fimage%2FMilestoneBAF2023_EN.jpg&amp;w=1080&amp;q=75 1080w, /_next/image?url=%2Fstatic%2Fimages%2Fimage%2FMilestoneBAF2023_EN.jpg&amp;w=1200&amp;q=75 1200w, /_next/image?url=%2Fstatic%2Fimages%2Fimage%2FMilestoneBAF2023_EN.jpg&amp;w=1920&amp;q=75 1920w, /_next/image?url=%2Fstatic%2Fimages%2Fimage%2FMilestoneBAF2023_EN.jpg&amp;w=2048&amp;q=75 2048w, /_next/image?url=%2Fstatic%2Fimages%2Fimage%2FMilestoneBAF2023_EN.jpg&amp;w=3840&amp;q=75 3840w</value>
      <webElementGuid>3eea0d7c-eb04-4b3d-896b-9b4dfdeabdfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fstatic%2Fimages%2Fimage%2FMilestoneBAF2023_EN.jpg&amp;w=3840&amp;q=75</value>
      <webElementGuid>d6bd4b29-7a10-47c3-aaa9-1c6eee33a7d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;about&quot;)/div[@class=&quot;image-container w-100 pb-4 d-flex justify-content-center&quot;]/img[@class=&quot;image&quot;]</value>
      <webElementGuid>a856d3df-43ea-4519-be4b-b40608cd9205</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='about']/div/img</value>
      <webElementGuid>7535889d-626b-4660-b1be-d23babc87821</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='MilestoneBaf2023EN']</value>
      <webElementGuid>1756236a-a460-46a6-a048-25a03423b165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/img</value>
      <webElementGuid>896da5a8-a7e2-4ad0-9ef6-13d6beb6f03a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'MilestoneBaf2023EN' and @src = '/_next/image?url=%2Fstatic%2Fimages%2Fimage%2FMilestoneBAF2023_EN.jpg&amp;w=3840&amp;q=75']</value>
      <webElementGuid>22565c23-707f-4f5b-bbc1-f184360f252e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
