<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Building</name>
   <tag></tag>
   <elementGuidId>b3e655c7-433e-4550-a4b3-09ea7243356b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[1]/main[1]/main[1]/div[2]/div[1]/div[1]/img[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.font-weight-bold.pt-4.pb-5.col-lg-4 > div > img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@srcset = '/_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fbaf_plaza_fq.webp&amp;w=640&amp;q=75 1x, /_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fbaf_plaza_fq.webp&amp;w=828&amp;q=75 2x' and @src = '/_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fbaf_plaza_fq.webp&amp;w=828&amp;q=75']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.font-weight-bold > div > img</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1503fbdc-5644-4d2c-9e48-40fc6b4d3cab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>8b8cd6b0-7b68-4e36-a01b-d0a58bc83797</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>400</value>
      <webElementGuid>bfdeb454-cbc3-4f8f-b479-9d07f5b43b0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>037a6147-f391-4114-b257-21b5982450c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>a218f7bd-6327-48d3-9000-37a0c669f814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>79cb6d8c-f6c3-4801-b712-b75890611ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fbaf_plaza_fq.webp&amp;w=640&amp;q=75 1x, /_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fbaf_plaza_fq.webp&amp;w=828&amp;q=75 2x</value>
      <webElementGuid>0a809038-6fbb-42c9-88b0-25ae8d21cacd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fbaf_plaza_fq.webp&amp;w=828&amp;q=75</value>
      <webElementGuid>2e9de4f8-4e40-4803-ada1-98e3c0e8fa47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__className_4df22e&quot;]/main[@class=&quot;layout&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;font-weight-bold pt-4 pb-5 col-lg-4&quot;]/div[1]/img[1]</value>
      <webElementGuid>e439420a-2553-46c7-a170-726c90b22a66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[2]/div/div/img</value>
      <webElementGuid>8083a195-4919-422c-abe9-c407034938fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/img</value>
      <webElementGuid>7fce2ba2-ca81-467f-a030-ffcd6e4308ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fbaf_plaza_fq.webp&amp;w=828&amp;q=75']</value>
      <webElementGuid>924186f0-06cb-4f89-9743-38fa20758cbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
