<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_JA Mitsui Leasing, Ltd</name>
   <tag></tag>
   <elementGuidId>ea745c38-a2f2-405f-b1fb-504c413320c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shareholder']/div/div/div/div/div/ul/li[2]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=&quot;20,0%JA Mitsui Leasing, Ltd.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f3c5edd6-7c36-4aee-80b7-f506951913b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-0</value>
      <webElementGuid>d23f49ce-208c-4d80-b2d6-6b713d68966a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20,0%JA Mitsui Leasing, Ltd.</value>
      <webElementGuid>6a6cab71-4002-458b-938c-fb615518f21f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shareholder&quot;)/div[@class=&quot;text-center txt-blue-baf&quot;]/div[@class=&quot;p-0 row&quot;]/div[@class=&quot;pt-4 pl-0 pr-0 col&quot;]/div[@class=&quot;tree&quot;]/div[@class=&quot;d-flex justify-content-center p-0 m-0&quot;]/ul[@class=&quot;w-100 container-stackholderr p-0&quot;]/li[@class=&quot;container-stackholder&quot;]/a[@class=&quot;border-0&quot;]</value>
      <webElementGuid>5c7a3fcd-ab7e-41d8-83bd-04dc1ace7fc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shareholder']/div/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>9e752177-ba2e-4f53-bf43-b36ede8a376e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHAREHOLDERS'])[1]/following::a[2]</value>
      <webElementGuid>c32dbdb7-9e87-49f9-a293-9ea4b13031b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toshiyuki Kojima'])[1]/preceding::a[5]</value>
      <webElementGuid>d819f892-2e28-4ff0-817d-6c4c9b8f5bda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read More >>>'])[1]/preceding::a[5]</value>
      <webElementGuid>2f87510b-c37c-405f-bf29-cff741e9684f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>893a962b-4e2a-429d-b3cb-5131032376ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '20,0%JA Mitsui Leasing, Ltd.' or . = '20,0%JA Mitsui Leasing, Ltd.')]</value>
      <webElementGuid>00f51928-fdce-4be9-ae68-1ca7a479b544</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
