<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Mitsui  Co., Ltd</name>
   <tag></tag>
   <elementGuidId>949236c3-0cc7-4031-9230-b40d0f83bbf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='shareholder']/div/div/div/div/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.border-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>a >> internal:has-text=&quot;45,0%Mitsui &amp; Co., Ltd.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b8cae52c-4a9f-4025-9bac-1d5341bff0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-0</value>
      <webElementGuid>d2798c4c-17d5-4df9-8c87-6c8e9658f39d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>45,0%Mitsui &amp; Co., Ltd.</value>
      <webElementGuid>3823593a-86b8-44ff-a201-b03a6ca62d31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;shareholder&quot;)/div[@class=&quot;text-center txt-blue-baf&quot;]/div[@class=&quot;p-0 row&quot;]/div[@class=&quot;pt-4 pl-0 pr-0 col&quot;]/div[@class=&quot;tree&quot;]/div[@class=&quot;d-flex justify-content-center p-0 m-0&quot;]/ul[@class=&quot;w-100 container-stackholderr p-0&quot;]/li[@class=&quot;container-stackholder&quot;]/a[@class=&quot;border-0&quot;]</value>
      <webElementGuid>201c7c0a-f32b-4493-9c8e-708324fac065</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='shareholder']/div/div/div/div/div/ul/li/a</value>
      <webElementGuid>1fa72a2a-95c8-4217-9940-01b56d0fa827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHAREHOLDERS'])[1]/following::a[1]</value>
      <webElementGuid>cbd338f2-8594-4168-a63c-6535506c0883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toshiyuki Kojima'])[1]/preceding::a[6]</value>
      <webElementGuid>115f1759-1def-403a-9261-f1bf7ac603b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Read More >>>'])[1]/preceding::a[6]</value>
      <webElementGuid>35c47a05-8b81-456d-b3b5-802712d5b5c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>99cabe4e-c3a0-491a-b56c-a5545969c057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '45,0%Mitsui &amp; Co., Ltd.' or . = '45,0%Mitsui &amp; Co., Ltd.')]</value>
      <webElementGuid>d2b21fa0-1c66-423f-a2d3-f1f2f98c46af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
