<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Organization Structure PT Bussan Auto Finance</name>
   <tag></tag>
   <elementGuidId>5f3c6554-7cc3-4b42-9c9c-c4cfc4ae50d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='organization']/div/div/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.text-center.d-flex.flex-column.align-items-center.container > div.image-container.w-100 > img.image</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;structure-organization&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d7ca976b-10f4-458c-b5f0-283451c07d7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>structure-organization</value>
      <webElementGuid>b6b239e3-f1ef-47a0-aef9-60185cf46a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>04d03b6c-e95d-405a-aef3-461cc8d665e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>68285939-abd2-4ef5-8673-98ac7d37a3be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>fill</value>
      <webElementGuid>e08cdc2b-6ea0-4cd6-959c-9678572b0b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>image</value>
      <webElementGuid>fdf5850f-a936-473e-a5b9-c343aa0f8b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>sizes</name>
      <type>Main</type>
      <value>100vw</value>
      <webElementGuid>1386b66a-492e-4065-9e2c-bc3eefc91499</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fstructure-organization.png&amp;w=640&amp;q=75 640w, /_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fstructure-organization.png&amp;w=750&amp;q=75 750w, /_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fstructure-organization.png&amp;w=828&amp;q=75 828w, /_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fstructure-organization.png&amp;w=1080&amp;q=75 1080w, /_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fstructure-organization.png&amp;w=1200&amp;q=75 1200w, /_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fstructure-organization.png&amp;w=1920&amp;q=75 1920w, /_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fstructure-organization.png&amp;w=2048&amp;q=75 2048w, /_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fstructure-organization.png&amp;w=3840&amp;q=75 3840w</value>
      <webElementGuid>f0015970-7366-422a-9f39-4f35004d4594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fstructure-organization.png&amp;w=3840&amp;q=75</value>
      <webElementGuid>eaa2143a-4161-4ceb-9dd9-242d4bedb4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;organization&quot;)/div[@class=&quot;text-center d-flex flex-column align-items-center container&quot;]/div[@class=&quot;image-container w-100&quot;]/img[@class=&quot;image&quot;]</value>
      <webElementGuid>d607b520-473e-4675-b3b5-8c2d2f91f649</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='organization']/div/div/img</value>
      <webElementGuid>5e8637ae-9735-4cc6-b226-3fb7d155e53e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='structure-organization']</value>
      <webElementGuid>236137f7-4e24-496c-843c-e80cb646372f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/img</value>
      <webElementGuid>01c043c7-3da9-4eb3-b927-7b8fa82658cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'structure-organization' and @src = '/_next/image?url=%2Fstatic%2Fimages%2Fimage%2Fstructure-organization.png&amp;w=3840&amp;q=75']</value>
      <webElementGuid>3fd7266c-9208-41ec-a715-4d29b6dea005</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
