<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Vision, Mission, and Value</name>
   <tag></tag>
   <elementGuidId>52e1e6fe-24f6-4042-ab5f-14c8e240980c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='product-tab-tab-visimisi']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product-tab-tab-visimisi</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;VISION, MISSION, &amp; VALUES&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5d182c81-374c-4e6a-a6aa-0ac89f870f15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>locale</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>9823a21f-6e97-4a3a-b5dd-64c89831fcb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>003ca71f-544f-4284-8d42-9f4ed28d3c5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>394dda4c-3ca3-45d2-9da9-65abe5024ca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rb-event-key</name>
      <type>Main</type>
      <value>visimisi</value>
      <webElementGuid>a43f59eb-b0f5-4900-9b26-3d63e9d5df6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-tab-tab-visimisi</value>
      <webElementGuid>1cfe27e3-4c5e-45f2-b7d3-76b6468ec647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>product-tab-tabpane-visimisi</value>
      <webElementGuid>2984c0f9-b26f-41d2-bdb1-4bc30b6ea34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3e015ea9-e02b-462b-92bb-2d0171d46b1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt-blue-baf nav-link</value>
      <webElementGuid>fd990ff0-283e-43a1-987f-13bdf1605539</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VISION, MISSION, &amp; VALUES</value>
      <webElementGuid>3d46ce60-203d-432c-8f16-868739c38de1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-tab-tab-visimisi&quot;)</value>
      <webElementGuid>233f0a9a-02bd-410f-9c8c-d9522529ca3b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='product-tab-tab-visimisi']</value>
      <webElementGuid>260a697f-b5f7-4eb0-8301-4c53d4f0395a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[2]/div/div[2]/div/div[2]/a</value>
      <webElementGuid>a5013c82-3695-4f19-a40c-259437e12b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'VISION, MISSION, &amp; VALUES')]</value>
      <webElementGuid>db0ecf7c-cb99-4afa-b98a-8e7f3d3bee88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::a[2]</value>
      <webElementGuid>62c81576-b3bc-47e9-9bca-52f5645b9d84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/following::a[3]</value>
      <webElementGuid>19af2264-0283-4052-92ce-dde6486d666e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORGANIZATION STRUCTURE'])[2]/preceding::a[6]</value>
      <webElementGuid>5bc49e78-a388-484d-92ab-c5918963f155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VISION, MISSION, &amp; VALUES']/parent::*</value>
      <webElementGuid>63400191-96af-47a4-b91f-e394c54c275b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[9]</value>
      <webElementGuid>2236d1c7-f295-4421-9778-f33b23dd2e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/a</value>
      <webElementGuid>0a7975c6-db43-49ab-8a52-bc6b354b8500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'product-tab-tab-visimisi' and (text() = 'VISION, MISSION, &amp; VALUES' or . = 'VISION, MISSION, &amp; VALUES')]</value>
      <webElementGuid>e569032f-5e0e-4fed-9d88-97385599f6cd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
