<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Board of Commissioners</name>
   <tag></tag>
   <elementGuidId>eac50fc4-941b-4888-8b7c-474d1bad7bed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='product-tab-tab-commissioner']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#product-tab-tab-commissioner</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;BOARD OF COMMISSIONERS&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f5b0b377-aecf-437f-a0f3-2c2e24c7c754</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>locale</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>e9dd4f8a-5f0a-4fd2-adbc-37fce64647c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>659a8c80-5eb2-42ee-b4a1-2ed4490bd73e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>f5ca4c0d-6277-446f-9ce0-24d83fd8c6e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rb-event-key</name>
      <type>Main</type>
      <value>commissioner</value>
      <webElementGuid>13df0b54-705d-4fa7-9b05-03f1d906d961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>product-tab-tab-commissioner</value>
      <webElementGuid>82c187b8-2a4f-4cc8-b91e-153af4b6a2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>product-tab-tabpane-commissioner</value>
      <webElementGuid>53aaddcd-a20b-4e9b-bee8-8cfbc53f114b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>81e2fd1a-6dbc-487c-af5a-e0a172d866b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt-blue-baf nav-link</value>
      <webElementGuid>01fee99f-1aba-4a12-8aad-82b8c174ac9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BOARD OF COMMISSIONERS</value>
      <webElementGuid>3968a573-c838-4d30-a11e-a5ddb994829b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-tab-tab-commissioner&quot;)</value>
      <webElementGuid>ceed8186-31b0-4690-9d90-584da0072ef8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='product-tab-tab-commissioner']</value>
      <webElementGuid>bc10df2d-b1ff-4015-b2f1-90c84eabd1f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[2]/div/div[2]/div/div[5]/a</value>
      <webElementGuid>094143d7-d883-48ce-a66e-4f5c46371130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'BOARD OF COMMISSIONERS')]</value>
      <webElementGuid>a2c07a0c-eb2d-449d-a8a2-7ff710176924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::a[5]</value>
      <webElementGuid>5d155551-b038-4ddd-b51d-df47eae7b1e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/following::a[6]</value>
      <webElementGuid>3b35e82a-b833-41e4-8341-c30430fb9068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORGANIZATION STRUCTURE'])[2]/preceding::a[3]</value>
      <webElementGuid>a52cbc19-7347-4444-9dac-a3806631fa25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BOARD OF COMMISSIONERS']/parent::*</value>
      <webElementGuid>b229cb1f-a9bf-4175-b468-53238055e736</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[12]</value>
      <webElementGuid>b7ff07dc-d6e7-476c-9df1-b88b76cf8562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[5]/a</value>
      <webElementGuid>6f07856c-76d1-4155-9e3e-ad83e51c30e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'product-tab-tab-commissioner' and (text() = 'BOARD OF COMMISSIONERS' or . = 'BOARD OF COMMISSIONERS')]</value>
      <webElementGuid>f8113e24-d4df-4209-a113-b9ab93582a5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
