<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_BAF</name>
   <tag></tag>
   <elementGuidId>5ec20d6e-79b0-47f8-9675-5949c5777533</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.d-inline-block.align-top.nav-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/main/nav/div/div/a/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;BAF logo&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fb4951db-5731-4920-992d-d910861388fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/images/logos/baf.svg</value>
      <webElementGuid>0b689fbc-e7b8-4a5c-9824-0e75d5ce794c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-inline-block align-top nav-icon</value>
      <webElementGuid>61612583-4cfd-4351-a767-424bfb3b819a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>BAF logo</value>
      <webElementGuid>4f5ef9eb-fc12-47b1-8824-5225c4572381</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__className_4df22e&quot;]/main[@class=&quot;layout&quot;]/nav[@class=&quot;navbar navbar-expand-lg navbar-light bg-light sticky-top&quot;]/div[1]/div[@class=&quot;d-flex flex-row&quot;]/a[1]/a[@class=&quot;navbar-brand&quot;]/img[@class=&quot;d-inline-block align-top nav-icon&quot;]</value>
      <webElementGuid>7c65fcf3-7b2f-43ca-8d21-a8d672cf3c08</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/nav/div/div/a/a/img</value>
      <webElementGuid>95731825-bf29-4d62-810d-6ff72011e8a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='BAF logo']</value>
      <webElementGuid>b28c2088-8575-454f-b92c-b426f69376cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>7dc71c13-bafe-4403-a6bd-8a6c4771f737</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/images/logos/baf.svg' and @alt = 'BAF logo']</value>
      <webElementGuid>d05a242d-50dd-4a8f-9c06-352259a100ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
