<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Career</name>
   <tag></tag>
   <elementGuidId>4ec88d1d-d2f4-40e3-85ff-025abccc5d86</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(3) > a.txt-blue-baf.nav-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/main/nav/div/div/div/div/div/div/a[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=navigation >> internal:text=&quot;Career&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a5e3199e-5683-448e-862f-65d482161fbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>locale</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>6e59b48c-8a47-4b5a-8f67-d6d8b20cb853</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/career</value>
      <webElementGuid>cd78a6cb-4312-4627-ab16-e43ad2a16289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rb-event-key</name>
      <type>Main</type>
      <value>/career</value>
      <webElementGuid>db4eff07-387c-459e-b620-b7a52771a4df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt-blue-baf nav-link</value>
      <webElementGuid>45834b4f-6ebc-4ccf-b7a6-e60247b6b5f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Career</value>
      <webElementGuid>06d680e3-1e75-4771-bce2-5ed067305925</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__className_4df22e&quot;]/main[@class=&quot;layout&quot;]/nav[@class=&quot;navbar navbar-expand-lg navbar-light bg-light sticky-top&quot;]/div[1]/div[@class=&quot;d-flex flex-row&quot;]/div[@class=&quot;nav-section w-100&quot;]/div[@class=&quot;navbar-collapse collapse&quot;]/div[@class=&quot;n-width align-items-center navbar-nav&quot;]/div[1]/a[3]/a[@class=&quot;txt-blue-baf nav-link&quot;]</value>
      <webElementGuid>7c2f6a28-c914-407d-844a-5ea56ac6c72f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/nav/div/div/div/div/div/div/a[3]/a</value>
      <webElementGuid>11aa37ea-4279-481b-b14e-b4a432c6f52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Career')]</value>
      <webElementGuid>52466ef7-72c0-4c54-8bca-480f5174bb85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporate'])[1]/following::a[2]</value>
      <webElementGuid>8ebb362e-0fe6-41be-bcef-a52b1da27cca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[1]/following::a[4]</value>
      <webElementGuid>ae4e9295-d0b0-41ff-8660-d73dcd5ad371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::a[1]</value>
      <webElementGuid>07708b76-1705-4036-931e-996ef6ee6a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='|'])[1]/preceding::a[3]</value>
      <webElementGuid>0cd2f585-56e8-4d8a-b2e5-9ba9de1cae44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Career']/parent::*</value>
      <webElementGuid>793279bc-b14f-4dd0-a0a3-91e4ba585206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/career')])[2]</value>
      <webElementGuid>a79673ef-b948-4e58-a8c6-1487205054d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/a</value>
      <webElementGuid>6ac058e9-e5ef-480c-a711-ab3b9728806b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/career' and (text() = 'Career' or . = 'Career')]</value>
      <webElementGuid>50132c41-9cb0-4e28-a776-68333b66b3cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
