<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Corporate</name>
   <tag></tag>
   <elementGuidId>ebe86ab9-f267-40c9-9e97-13c732ec2188</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(2) > a.txt-blue-baf.nav-link</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/main/nav/div/div/div/div/div/div/a[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=navigation >> internal:text=&quot;Corporate&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>8dacf242-a924-4c69-9fb3-bf9a87c2d625</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>locale</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>825d67f5-6146-41bf-ac94-99bdff5e426b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/corporate</value>
      <webElementGuid>9e9d2ec3-2d35-4e7b-85e5-ae4be6a25729</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rb-event-key</name>
      <type>Main</type>
      <value>/corporate</value>
      <webElementGuid>a7e83e23-b76a-40e7-bfd6-724b7d4eee76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt-blue-baf nav-link</value>
      <webElementGuid>e21d2777-0b45-492d-809e-fafbd5cc4e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Corporate</value>
      <webElementGuid>ca972a5e-2299-4bc7-8903-30265fe89d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__className_4df22e&quot;]/main[@class=&quot;layout&quot;]/nav[@class=&quot;navbar navbar-expand-lg navbar-light bg-light sticky-top&quot;]/div[1]/div[@class=&quot;d-flex flex-row&quot;]/div[@class=&quot;nav-section w-100&quot;]/div[@class=&quot;navbar-collapse collapse&quot;]/div[@class=&quot;n-width align-items-center navbar-nav&quot;]/div[1]/a[2]/a[@class=&quot;txt-blue-baf nav-link&quot;]</value>
      <webElementGuid>b7f4d8e5-2aab-4a08-a07f-48c867311f8e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/nav/div/div/div/div/div/div/a[2]/a</value>
      <webElementGuid>f4504261-0a45-4b5d-bf4f-4b91d27fa2d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Corporate')]</value>
      <webElementGuid>f1b84b56-b769-4d06-a675-155e9cf5f776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer'])[1]/following::a[2]</value>
      <webElementGuid>defe74e3-175a-4f96-81bd-3ca4206696fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Career'])[1]/preceding::a[1]</value>
      <webElementGuid>cd71b049-db2b-4c1d-b752-f81127517323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/preceding::a[3]</value>
      <webElementGuid>4ebf8db3-81dd-4381-ac46-52c4174c1a6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Corporate']/parent::*</value>
      <webElementGuid>6de75d47-be86-41c7-8eb2-41396bfa22a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/corporate')])[2]</value>
      <webElementGuid>97717b44-0e0d-40ee-bc12-31ca0596471b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/a</value>
      <webElementGuid>a97a1699-2bad-437d-8d6f-647f0d5835a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/corporate' and (text() = 'Corporate' or . = 'Corporate')]</value>
      <webElementGuid>2f921ac4-5b89-4b1d-8c35-204aa0e88cf4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
