<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Internal Audit Unit</name>
   <tag></tag>
   <elementGuidId>c29298bb-ce14-408b-b4fe-42b750a00152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(9) > a.dropdown-item</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='basic-navbar-nav']/div/div/div/div[2]/div/a[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Internal Audit Unit&quot;i] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6179b697-782f-45d9-9182-cc68cf343f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/corporate/CorporateGovernance/InternalAudit</value>
      <webElementGuid>1204434c-dac2-4f69-926b-e53775cd9abf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-item</value>
      <webElementGuid>520c7f59-cf73-4337-be9c-a2d278103aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Internal Audit Unit</value>
      <webElementGuid>06d977d4-c44e-4e11-adcc-5d18b700d9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;basic-navbar-nav&quot;)/div[@class=&quot;n-width align-items-center navbar-nav&quot;]/div[1]/div[@class=&quot;d-flex flex-row&quot;]/div[@class=&quot;txt-blue-baf nav-item show dropdown&quot;]/div[@class=&quot;dropdown-menu show&quot;]/a[9]/a[@class=&quot;dropdown-item&quot;]</value>
      <webElementGuid>dfc48e19-1cd6-4c4b-8d28-e65fdfe31493</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='basic-navbar-nav']/div/div/div/div[2]/div/a[9]/a</value>
      <webElementGuid>cc2337aa-24c1-463e-b961-2dd67d23c440</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporate Secretary'])[1]/following::a[2]</value>
      <webElementGuid>8d1d92d5-f85a-434e-8989-a8bf8c63cc6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Committees under BOD'])[1]/following::a[4]</value>
      <webElementGuid>772905c3-e0f1-48bd-bf15-6b60ee34b598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Whistleblowing System'])[1]/preceding::a[1]</value>
      <webElementGuid>ec4fb49f-49c1-4cd9-867a-158aa0fc185b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/corporate/CorporateGovernance/InternalAudit')])[2]</value>
      <webElementGuid>f1a80941-a26f-42ce-b1a3-637f1eec5c33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[9]/a</value>
      <webElementGuid>3b17b130-ae0f-40e8-bce4-ca823d6e1231</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/corporate/CorporateGovernance/InternalAudit' and (text() = 'Internal Audit Unit' or . = 'Internal Audit Unit')]</value>
      <webElementGuid>d068d9a7-22cb-4490-a1ca-32f7e220ada2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
