<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Customer</name>
   <tag></tag>
   <elementGuidId>abab56fd-63c4-4b22-b240-4d59379553ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/main/nav/div/div/div/div/div/div/a/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.txt-blue-baf.nav-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=navigation >> internal:text=&quot;Customer&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>70dcef08-f051-4e70-8dff-520469f576ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>locale</name>
      <type>Main</type>
      <value>en</value>
      <webElementGuid>a89e89e4-1524-4bb3-8ab4-b0e3dff4f527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>b0a88f51-73ee-4165-8a3b-75ef7575ac19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rb-event-key</name>
      <type>Main</type>
      <value>/</value>
      <webElementGuid>921283dc-d312-4e1b-8386-023172b9fd2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>txt-blue-baf nav-link</value>
      <webElementGuid>fef4c641-ff11-43b3-bb92-bdf8f668e016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer</value>
      <webElementGuid>9a77849a-531a-4430-abfc-6c623bf95e37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__className_4df22e&quot;]/main[@class=&quot;layout&quot;]/nav[@class=&quot;navbar navbar-expand-lg navbar-light bg-light sticky-top&quot;]/div[1]/div[@class=&quot;d-flex flex-row&quot;]/div[@class=&quot;nav-section w-100&quot;]/div[@class=&quot;navbar-collapse collapse&quot;]/div[@class=&quot;n-width align-items-center navbar-nav&quot;]/div[1]/a[1]/a[@class=&quot;txt-blue-baf nav-link&quot;]</value>
      <webElementGuid>28ea60d9-77d4-4144-9fb5-0aeabdaa5169</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/nav/div/div/div/div/div/div/a/a</value>
      <webElementGuid>f6e042bd-9c0f-4f7d-9203-a7f69f2de27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Customer')]</value>
      <webElementGuid>51d641f5-f92a-49c5-b0a8-22d665b1b9c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Corporate'])[1]/preceding::a[1]</value>
      <webElementGuid>17aa38bb-fd58-4c30-b77b-18335f71b98d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Career'])[1]/preceding::a[3]</value>
      <webElementGuid>5be577af-0d05-480d-9855-584c98c15995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Customer']/parent::*</value>
      <webElementGuid>753e6ba0-6719-42ba-a956-47f199e2ddba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '/')])[4]</value>
      <webElementGuid>f6034806-d220-40f3-ae99-957c17ac4325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/a/a</value>
      <webElementGuid>b41c2131-97ec-4e38-a202-95eecbcaef8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/' and (text() = 'Customer' or . = 'Customer')]</value>
      <webElementGuid>f01b2078-2470-4419-9c83-09db90177193</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
