<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_Tahun</name>
   <tag></tag>
   <elementGuidId>4f38e19e-bc92-4e4d-81b0-2ec88594f04f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[1]/main[1]/main[1]/div[2]/div[3]/nav[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>nav.d-block.px-0.navbar.navbar-expand.navbar-light</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;20242023202220212020201920182017INFORMASI TAMBAHAN RINGKAS / SUMMARY OF ADDITION&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>nav</value>
      <webElementGuid>358e79ca-4c3e-4dd9-a391-aa7d4d5f2855</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-block px-0 navbar navbar-expand navbar-light</value>
      <webElementGuid>e9d29272-5202-4ac3-b1c4-91c91c41d91f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>20242023202220212020201920182017INFORMASI TAMBAHAN RINGKAS / SUMMARY OF ADDITIONAL INFORMATION - PUB III-II 2024INFORMASI TAMBAHAN RINGKAS / SUMMARY OF ADDITIONAL INFORMATION - PUB III-I 2024PROSPEKTUS / PROSPECTUS - PUB III-I 2024PROSPEKTUS RINGKAS / SUMMARY OF PROSPECTUS - PUB III-I 2024</value>
      <webElementGuid>af7ccc2a-6270-4e70-ac63-2a137e9b860a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__className_4df22e&quot;]/main[@class=&quot;layout&quot;]/div[2]/div[3]/nav[@class=&quot;d-block px-0 navbar navbar-expand navbar-light&quot;]</value>
      <webElementGuid>c39b5d56-0e03-49c4-ae39-c131bf0caf60</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[2]/div[3]/nav</value>
      <webElementGuid>a01bcee2-fabc-421f-be89-0494373dc4f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOND INFORMATION'])[1]/following::nav[1]</value>
      <webElementGuid>d6cc0258-c0d4-4847-b842-2afad48325d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::nav[1]</value>
      <webElementGuid>5f1da424-f2e7-4a26-ae5b-e7cd77a05614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/nav</value>
      <webElementGuid>1e2e3b9a-65fe-402b-9596-bfd5c841b83f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//nav[(text() = '20242023202220212020201920182017INFORMASI TAMBAHAN RINGKAS / SUMMARY OF ADDITIONAL INFORMATION - PUB III-II 2024INFORMASI TAMBAHAN RINGKAS / SUMMARY OF ADDITIONAL INFORMATION - PUB III-I 2024PROSPEKTUS / PROSPECTUS - PUB III-I 2024PROSPEKTUS RINGKAS / SUMMARY OF PROSPECTUS - PUB III-I 2024' or . = '20242023202220212020201920182017INFORMASI TAMBAHAN RINGKAS / SUMMARY OF ADDITIONAL INFORMATION - PUB III-II 2024INFORMASI TAMBAHAN RINGKAS / SUMMARY OF ADDITIONAL INFORMATION - PUB III-I 2024PROSPEKTUS / PROSPECTUS - PUB III-I 2024PROSPEKTUS RINGKAS / SUMMARY OF PROSPECTUS - PUB III-I 2024')]</value>
      <webElementGuid>bcf87009-8cc5-40a9-9065-86731912a68d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
