<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Financial Insight</name>
   <tag></tag>
   <elementGuidId>3e8c06dc-ef21-4335-9ee3-876fdef0f152</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#news-tab-tab-KEUANGAN</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='news-tab-tab-KEUANGAN']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Financial Insight&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0884cc9a-39b6-4a46-8f4b-f6f37811aa20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f9dd660e-ab0c-4fc8-b013-b35e45e8ba65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>472d5ae3-d56a-4a18-84ad-26f06e9c0ac6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rb-event-key</name>
      <type>Main</type>
      <value>KEUANGAN</value>
      <webElementGuid>08e6bfe1-a384-44aa-b5bc-7576a4404b0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>news-tab-tab-KEUANGAN</value>
      <webElementGuid>6da42f55-3792-4a4f-82bd-6f273326fe3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>news-tab-tabpane-KEUANGAN</value>
      <webElementGuid>39e3e740-5916-4a28-90fb-28c0183dc0af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>6c223932-5dc1-46fc-9112-cb278612657b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-news-link nav-link</value>
      <webElementGuid>48479918-21ff-47e9-aac2-984b80dd4b5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Financial Insight</value>
      <webElementGuid>9fc1b2c0-6cec-47a9-88a9-35ae2a7f1e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;news-tab-tab-KEUANGAN&quot;)</value>
      <webElementGuid>9288d376-5f37-4be5-aa28-d241086aad07</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='news-tab-tab-KEUANGAN']</value>
      <webElementGuid>6a64d841-7c5f-4d85-8a19-63fe178fc1fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div/div/div/div/div[4]/a</value>
      <webElementGuid>93118065-8c78-447a-9617-27ee7048e48e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Financial Insight')]</value>
      <webElementGuid>bdfcab92-92c9-4332-b2fd-7c89a6eb3b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAF Mobile'])[1]/following::a[4]</value>
      <webElementGuid>a0e1a648-aaea-4a80-b06b-806e9e73d6b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Articles'])[1]/following::a[6]</value>
      <webElementGuid>bbb6c18e-f022-4f71-ae74-097b8455e54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General'])[2]/preceding::a[2]</value>
      <webElementGuid>fb556c25-ee43-439c-b39f-d743ec5f71e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gini Cara Mudah Redeem BAF Points ke Cicilan'])[1]/preceding::a[2]</value>
      <webElementGuid>970877ef-9bb2-4ebf-abed-ab19bfed1d0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Financial Insight']/parent::*</value>
      <webElementGuid>5e695129-f2d2-42e0-a443-b9a206a064ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>72d3e6bd-3563-4dec-9e3a-7ae44aba0c79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>8528b873-6e6f-4d12-bb19-b03bc9adc540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'news-tab-tab-KEUANGAN' and (text() = 'Financial Insight' or . = 'Financial Insight')]</value>
      <webElementGuid>315b3718-30a8-437c-901e-20194da264f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
