<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_New Product</name>
   <tag></tag>
   <elementGuidId>7dc65afa-7285-46f5-85ef-6d63d5d27100</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#news-tab-tab-PRODUCT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='news-tab-tab-PRODUCT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;New Product&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5020ba81-04e1-43bd-9664-998cb8274c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a2267e62-a070-4956-88ab-45bf47dd3ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>d674d54a-735f-4778-a1e8-80f81c38d6d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rb-event-key</name>
      <type>Main</type>
      <value>PRODUCT</value>
      <webElementGuid>5f73611d-29e6-42ec-aecc-e4046b271c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>news-tab-tab-PRODUCT</value>
      <webElementGuid>893061e1-71a3-4ee5-928d-333f41531b0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>news-tab-tabpane-PRODUCT</value>
      <webElementGuid>b723a08f-c324-4e82-9c20-f5a2d8f114a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0f03140b-d1b3-4ed8-9278-d899c41fadff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-news-link nav-link</value>
      <webElementGuid>59647f76-76b2-4195-b26d-e85fb0dcf09d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Product</value>
      <webElementGuid>f4a933f0-6b5e-4e9f-b01d-975706978d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;news-tab-tab-PRODUCT&quot;)</value>
      <webElementGuid>319d4fef-4f96-43a8-ada7-b6a56d90dda7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='news-tab-tab-PRODUCT']</value>
      <webElementGuid>a17f333c-78d0-4aea-93c6-42b24d86abd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div/div/div/div/div[2]/a</value>
      <webElementGuid>ddadbab7-ac0e-4aa3-990e-5a0c7c610817</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'New Product')]</value>
      <webElementGuid>ba927b29-f6f7-4288-89cb-266f99620133</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAF Mobile'])[1]/following::a[2]</value>
      <webElementGuid>a3d60599-722b-4a61-a5ec-da111a2597c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Articles'])[1]/following::a[4]</value>
      <webElementGuid>64a90894-887a-4a5a-a0b5-80e7934d2dc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General'])[2]/preceding::a[4]</value>
      <webElementGuid>62a81d72-bc2f-407e-9ff2-03f71442805e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gini Cara Mudah Redeem BAF Points ke Cicilan'])[1]/preceding::a[4]</value>
      <webElementGuid>9a3afe37-bfcf-4149-b435-1d3b23c826fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New Product']/parent::*</value>
      <webElementGuid>da5cf77b-5eb2-457b-8a90-b10fbb480692</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[3]</value>
      <webElementGuid>fcaaf322-10c1-48c6-8130-3dbdfc2ca3b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>1c8ef213-d957-4165-8491-8fd35837cdfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'news-tab-tab-PRODUCT' and (text() = 'New Product' or . = 'New Product')]</value>
      <webElementGuid>5c63f2ea-cb4b-49a0-a443-e79598da8de1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
