<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Divident Policy</name>
   <tag></tag>
   <elementGuidId>07182aa6-2080-4efd-8990-41eb6f4b4148</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/main/div[2]/div[4]/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mx-5 > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;__next&quot;] div >> internal:has-text=&quot;DIVIDEND PAYMENT POLICYDalam rangka memastikan pelaksanaan prinsip Tata Kelola P&quot;i >> internal:role=img >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0f4ef0a5-52d3-4220-847c-f629685f560b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://baf-mobile-dev.oss-ap-southeast-5.aliyuncs.com/banner/1713491017329.png</value>
      <webElementGuid>591c79b3-7508-422c-b73f-cfb789890570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__className_4df22e&quot;]/main[@class=&quot;layout&quot;]/div[2]/div[@class=&quot;mx-5&quot;]/img[1]</value>
      <webElementGuid>8e0e4825-e79a-4e57-8a14-b3ac3c611654</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[2]/div[4]/img</value>
      <webElementGuid>4646f76d-91b5-46b6-874f-b9f918d6ebe2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://baf-mobile-dev.oss-ap-southeast-5.aliyuncs.com/banner/1713491017329.png')]</value>
      <webElementGuid>a1a6b045-5ee6-4bd4-859f-c153b516422b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/img</value>
      <webElementGuid>fa9c2092-08cb-4944-a8e4-47967563869b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://baf-mobile-dev.oss-ap-southeast-5.aliyuncs.com/banner/1713491017329.png']</value>
      <webElementGuid>2086df67-121a-46a7-8e57-e60f4c26a58d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
