<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Content</name>
   <tag></tag>
   <elementGuidId>92210009-4a7b-4ae6-bb2a-8e66c2ef6003</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='viewer']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@title = 'Whistleblowing']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#viewer</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Whistleblowing&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>c19f1e37-dfa7-4c09-9597-3fcf6a300686</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>viewer</value>
      <webElementGuid>15690509-fbc6-46a0-a1e4-97500c03058a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-0</value>
      <webElementGuid>b0670d83-6d5c-4477-9eee-e5d8126ca186</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>7dd43b54-2f32-41b5-aa8b-95a521f9e6f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>41a9694d-bf8c-4567-a83f-53e68a777740</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://whistleblowing.baf.id/</value>
      <webElementGuid>65805bc1-e00d-4597-bf9e-b95780bff9bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Whistleblowing</value>
      <webElementGuid>8ed51738-4ff1-4f00-8b87-d369242ac894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewer&quot;)</value>
      <webElementGuid>35f02e65-ae3f-4913-9194-c09518cf7dba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='viewer']</value>
      <webElementGuid>504e506b-5b1f-4428-9994-2449d4dc75ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[2]/iframe</value>
      <webElementGuid>6b631680-bf0d-4758-abce-dc2480b42562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>269c49c9-aed3-4e6f-bf2e-7187642bbe3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'viewer' and @src = 'https://whistleblowing.baf.id/' and @title = 'Whistleblowing']</value>
      <webElementGuid>4db1bc6c-6a54-4b62-a0bf-e2739a54e7ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
