<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Content</name>
   <tag></tag>
   <elementGuidId>ee9d3d52-2115-41f0-a652-14b2eab3ac95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/main/div[2]/div[2]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Dewan Pengawas Syariah (DPS) adalah bagian dari organ Perseroan yang mempunyai t&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>11474a7d-20e2-49a5-af71-3771685725c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${text_id}</value>
      <webElementGuid>1824c299-3213-404c-9d74-f5b0acd6d9b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__className_4df22e&quot;]/main[@class=&quot;layout&quot;]/div[2]/div[@class=&quot;m-5 text-justify&quot;]/div[@class=&quot;justify-content-center corporate-description&quot;]/p[1]</value>
      <webElementGuid>e017e352-5272-4dee-8f9c-3ea8ebaf02a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[2]/div[2]/div/p</value>
      <webElementGuid>862d0a85-9468-4716-920a-e973f2632391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHARIA SUPERVISORY BOARD'])[1]/following::p[1]</value>
      <webElementGuid>c338bad4-a3ff-4368-981c-177d9549048a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::p[1]</value>
      <webElementGuid>1374f297-5d05-4a85-978f-4cf8b09a0d1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEWAN PENGAWAS SYARIAH / SHARIA SUPERVISORY BOARD'])[1]/preceding::p[2]</value>
      <webElementGuid>531255ee-7cf5-44af-8707-942a266aee5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Bussan Auto Finance'])[1]/preceding::p[2]</value>
      <webElementGuid>7cc11abe-5b7b-402e-88d7-662718b68414</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dewan Pengawas Syariah (DPS) adalah bagian dari organ Perseroan yang mempunyai tugas dan fungsi pengawasan terhadap penyelenggaraan kegiatan perseroan agar sesuai dengan prinsip syariah.']/parent::*</value>
      <webElementGuid>743b1677-e491-475f-8f4b-66fe0ccd9361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>8f774daf-bcd5-4174-aa6c-b6b95155030c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Dewan Pengawas Syariah (DPS) adalah bagian dari organ Perseroan yang mempunyai tugas dan fungsi pengawasan terhadap penyelenggaraan kegiatan perseroan agar sesuai dengan prinsip syariah.' or . = 'Dewan Pengawas Syariah (DPS) adalah bagian dari organ Perseroan yang mempunyai tugas dan fungsi pengawasan terhadap penyelenggaraan kegiatan perseroan agar sesuai dengan prinsip syariah.')]</value>
      <webElementGuid>c98ee95e-ad86-449a-b3cd-0600dc59a9ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
