<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Download</name>
   <tag></tag>
   <elementGuidId>faca6755-9f17-4793-ad39-ee2c040f55cc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='2024']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#2024</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\32 024&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>f97d1a4b-8638-45f6-bca9-c73dc2a440d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>${tahun_id}</value>
      <webElementGuid>bcc63d8e-1e29-4b39-ba6f-58edb0d1ed61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 p-3 my-3 cursor-pointer</value>
      <webElementGuid>6ae99abe-3047-43f5-af80-3a775ba2c068</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RAPAT UMUM PEMEGANG SAHAM 2024 / GENERAL MEETING OF SHAREHOLDERS 2024</value>
      <webElementGuid>9cf50cea-f0dc-4c66-98d0-09a7614312ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;2024&quot;)</value>
      <webElementGuid>adec369c-0335-43d4-9e27-90b17f22763d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='2024']</value>
      <webElementGuid>783536f8-e893-4562-98ed-01cd45a0f40a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[2]/nav/div[2]</value>
      <webElementGuid>c4c1f507-d338-4677-a49b-66fa56ae52cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GENERAL SHAREHOLDER MEETINGS'])[1]/following::div[5]</value>
      <webElementGuid>4672495b-9c33-4079-bfd4-e0cfc2601760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::div[7]</value>
      <webElementGuid>05ab007c-059d-4e4c-bac4-c8d3de679592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Bussan Auto Finance'])[1]/preceding::div[6]</value>
      <webElementGuid>469d5a9b-afd8-4096-9908-5191a580a33a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/nav/div[2]</value>
      <webElementGuid>cbcce4a0-b672-4b90-8cf6-e668ad121aae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '2024' and (text() = 'RAPAT UMUM PEMEGANG SAHAM 2024 / GENERAL MEETING OF SHAREHOLDERS 2024' or . = 'RAPAT UMUM PEMEGANG SAHAM 2024 / GENERAL MEETING OF SHAREHOLDERS 2024')]</value>
      <webElementGuid>4acaf7e9-bf16-4cab-b701-175257c76c6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
