<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Inggris</name>
   <tag></tag>
   <elementGuidId>7908014f-4da1-4051-9cda-cf2e49d19d05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/main/div[2]/div[2]/div/p[2]/em</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>em</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;General Meetings of Shareholders (GMS) is a Company Structure with the highest a&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>em</value>
      <webElementGuid>2800921c-202b-470a-8689-fa9d45e52a0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>General Meetings of Shareholders (GMS) is a Company Structure with the highest authority which is neither delegated to Board of Commissioners or Board of Directors according to limit as stipulated in the Limited Company Law and/or Articles of Association.</value>
      <webElementGuid>a625f65e-e06d-4bbe-8344-c9b2c4bf8956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__className_4df22e&quot;]/main[@class=&quot;layout&quot;]/div[2]/div[@class=&quot;m-5 text-justify&quot;]/div[@class=&quot;justify-content-center corporate-description&quot;]/p[2]/em[1]</value>
      <webElementGuid>ff4cd447-ea48-4f20-857c-ca3c4abc14e2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[2]/div[2]/div/p[2]/em</value>
      <webElementGuid>1c906c75-d116-43e3-9bdd-26613405ff96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GENERAL SHAREHOLDER MEETINGS'])[1]/following::em[1]</value>
      <webElementGuid>9e3a5f3d-b76c-494f-a82f-2c74fb67e1c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::em[1]</value>
      <webElementGuid>857cbd81-3583-4576-940a-a11a85e2be83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RAPAT UMUM PEMEGANG SAHAM 2024 / GENERAL MEETING OF SHAREHOLDERS 2024'])[1]/preceding::em[1]</value>
      <webElementGuid>c183c847-922b-4189-a083-fdd71c5ed169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Bussan Auto Finance'])[1]/preceding::em[1]</value>
      <webElementGuid>6a30b75e-448e-49e0-9510-a2a259edd4a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='General Meetings of Shareholders (GMS) is a Company Structure with the highest authority which is neither delegated to Board of Commissioners or Board of Directors according to limit as stipulated in the Limited Company Law and/or Articles of Association.']/parent::*</value>
      <webElementGuid>e7282c6e-5839-48d3-842f-f3d4278f9a91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//em</value>
      <webElementGuid>c95c4f2a-d0f3-49f5-972a-74137e2b1a98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//em[(text() = 'General Meetings of Shareholders (GMS) is a Company Structure with the highest authority which is neither delegated to Board of Commissioners or Board of Directors according to limit as stipulated in the Limited Company Law and/or Articles of Association.' or . = 'General Meetings of Shareholders (GMS) is a Company Structure with the highest authority which is neither delegated to Board of Commissioners or Board of Directors according to limit as stipulated in the Limited Company Law and/or Articles of Association.')]</value>
      <webElementGuid>135f1d27-b333-4496-bd5e-cfc25d43861c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
