<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lbl_Indonesia</name>
   <tag></tag>
   <elementGuidId>52e44963-527f-4d51-97f0-13385a7b923a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/main/div[2]/div[2]/div/p</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Rapat Umum Pemegang Saham (RUPS) adalah organ Perseroan yang memiliki wewenang t&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ff6509e5-bff6-4bdb-9279-dc8f6b1f9de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rapat Umum Pemegang Saham (RUPS) adalah organ Perseroan yang memiliki wewenang tertinggi yang tidak diberikan kepada Dewan Komisaris atau Direksi dalam batas yang ditentukan dalam Undang-Undang Perseroan Terbatas dan/atau Anggaran Dasar Perseroan.</value>
      <webElementGuid>d386848a-3f3b-4109-9385-43332e5baae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__className_4df22e&quot;]/main[@class=&quot;layout&quot;]/div[2]/div[@class=&quot;m-5 text-justify&quot;]/div[@class=&quot;justify-content-center corporate-description&quot;]/p[1]</value>
      <webElementGuid>ebd3042d-5352-4f7f-94e9-852514b62694</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[2]/div[2]/div/p</value>
      <webElementGuid>dc807250-03d1-4c0c-8286-98cb90d92e4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GENERAL SHAREHOLDER MEETINGS'])[1]/following::p[1]</value>
      <webElementGuid>cbc7ac7d-4a8f-42f8-8789-1b28bb00caf4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Next'])[1]/following::p[1]</value>
      <webElementGuid>e0f2ae30-e293-4c91-8f1d-dfc438efd7ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RAPAT UMUM PEMEGANG SAHAM 2024 / GENERAL MEETING OF SHAREHOLDERS 2024'])[1]/preceding::p[2]</value>
      <webElementGuid>69cc5c0a-7fde-4001-bf43-52da12fb3699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Bussan Auto Finance'])[1]/preceding::p[2]</value>
      <webElementGuid>4dfd8f5f-3ea5-461d-a202-89ede9fefa11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rapat Umum Pemegang Saham (RUPS) adalah organ Perseroan yang memiliki wewenang tertinggi yang tidak diberikan kepada Dewan Komisaris atau Direksi dalam batas yang ditentukan dalam Undang-Undang Perseroan Terbatas dan/atau Anggaran Dasar Perseroan.']/parent::*</value>
      <webElementGuid>05ab6d55-35aa-4359-8395-bbbf7f1ea1dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>a4bc10e0-ffa1-4d52-ac83-705ad07f2331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Rapat Umum Pemegang Saham (RUPS) adalah organ Perseroan yang memiliki wewenang tertinggi yang tidak diberikan kepada Dewan Komisaris atau Direksi dalam batas yang ditentukan dalam Undang-Undang Perseroan Terbatas dan/atau Anggaran Dasar Perseroan.' or . = 'Rapat Umum Pemegang Saham (RUPS) adalah organ Perseroan yang memiliki wewenang tertinggi yang tidak diberikan kepada Dewan Komisaris atau Direksi dalam batas yang ditentukan dalam Undang-Undang Perseroan Terbatas dan/atau Anggaran Dasar Perseroan.')]</value>
      <webElementGuid>dba703e7-8700-4f9a-a773-25642a54c254</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
