<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Content</name>
   <tag></tag>
   <elementGuidId>92210009-4a7b-4ae6-bb2a-8e66c2ef6003</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@id = 'viewer' and @src = 'https://whistleblowing.baf.id/' and @title = 'Whistleblowing']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#viewer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='viewer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Whistleblowing&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>062d7248-1c8c-431b-9bf2-dbe3c6adec34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>viewer</value>
      <webElementGuid>42d05cb8-0dff-4795-8097-1795f9ff7c12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-0</value>
      <webElementGuid>f2627812-b388-423f-83d7-e31ffae1dadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>5d1ff420-cc8e-4849-94a1-e695a411b36f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>d9f75f4a-20aa-487e-b7b6-d336f40aa8c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://whistleblowing.baf.id/</value>
      <webElementGuid>1df37235-8026-4138-8582-1a3e293689e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Whistleblowing</value>
      <webElementGuid>de04d3be-1bae-4b5f-a38d-e56a355a7f44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewer&quot;)</value>
      <webElementGuid>5b5699ed-6b97-4832-af96-acb19bc80d99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='viewer']</value>
      <webElementGuid>6976102a-cd7d-485e-b99e-4c746d6f5a5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[2]/iframe</value>
      <webElementGuid>39849d8f-1f78-4223-9806-19624f3546cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>ab4e6472-c553-44b9-8470-6a202961232b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'viewer' and @src = 'https://whistleblowing.baf.id/' and @title = 'Whistleblowing']</value>
      <webElementGuid>21947d80-97fc-471b-9b57-5e86353a44be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
