<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Content</name>
   <tag></tag>
   <elementGuidId>92210009-4a7b-4ae6-bb2a-8e66c2ef6003</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//iframe[@id = 'viewer' and @src = '${src}' and @title = '${tittle}']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#viewer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='viewer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;Whistleblowing&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>9fcc7887-94ff-4b79-ad0c-f47f1fc3a53e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>viewer</value>
      <webElementGuid>a86e6369-4727-4fb5-a203-518c0feba46a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-0</value>
      <webElementGuid>98f16f36-f0b0-4868-9b94-59fae6b55946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>800</value>
      <webElementGuid>9ce128bd-58e2-4726-b99c-888667156b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>74098ac1-2e41-47e8-b2ea-3a958eade215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>${src}</value>
      <webElementGuid>80fabc50-1fdb-403c-8c2c-3fdd3179f67c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>${tittle}</value>
      <webElementGuid>92de9aff-999e-4bd6-8ad5-8c52da7180ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;viewer&quot;)</value>
      <webElementGuid>b58ff12b-0d2b-4b21-84d5-5c4ebd918466</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='viewer']</value>
      <webElementGuid>6a7b995c-f275-43b8-b2a8-8a8fc4a73680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[2]/iframe</value>
      <webElementGuid>6eff690b-e593-4b0f-a864-5f61d09ce169</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>8a7db107-8750-4bee-ba44-d652ec1f7ae0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'viewer' and @src = 'https://whistleblowing.baf.id/' and @title = 'Whistleblowing']</value>
      <webElementGuid>b36f626c-9a12-4de1-86d0-b7e6a7fa9a55</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
