<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Agricultural Machinery</name>
   <tag></tag>
   <elementGuidId>2dbfef2a-7c5a-46c4-a8a6-12182267a512</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#news-tab-tab-AGRI</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='news-tab-tab-AGRI']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Agricultural Machinery&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6a297e0f-2bf5-48e4-9fce-433c4ddb70f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>fa8f5207-189d-4cef-a855-04c09e54c042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>476e7699-7b5c-43a7-bb68-087ba633cea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rb-event-key</name>
      <type>Main</type>
      <value>AGRI</value>
      <webElementGuid>ed0d53a3-c833-496e-a00a-6a82eba847ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>news-tab-tab-AGRI</value>
      <webElementGuid>7246513b-67d6-477e-80a2-0a3d548db9a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>news-tab-tabpane-AGRI</value>
      <webElementGuid>463bd804-1b97-413d-abc0-6bdc07e0a6d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>0d189812-ddbf-4ea0-a07f-28438166dec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-promoTabs nav-link</value>
      <webElementGuid>70b452b7-9c6e-4fce-9629-9c5af545ac43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Agricultural Machinery</value>
      <webElementGuid>280b5722-6574-4e8d-8b01-b7b92258a1eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;news-tab-tab-AGRI&quot;)</value>
      <webElementGuid>92a9dbe8-8ecb-472b-b6fd-b576d775107c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='news-tab-tab-AGRI']</value>
      <webElementGuid>8615acfa-775e-461d-b0c3-4f2e0a368998</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[2]/div/div/div[8]/a</value>
      <webElementGuid>46494719-e86c-402a-87c8-bdb94a2270c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Agricultural Machinery')]</value>
      <webElementGuid>b94732fa-9bbe-407f-9520-37ce4c0ab47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EVENT &amp; PROMO'])[1]/following::a[8]</value>
      <webElementGuid>704743b7-514b-4ea1-9b50-f9dcc87fe3a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAF Mobile'])[1]/following::a[8]</value>
      <webElementGuid>6db2ea87-52df-4aa6-89cb-2549a092b633</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Motor Baru'])[1]/preceding::a[2]</value>
      <webElementGuid>dfa42de3-31ea-4416-809a-d5f610c74d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emang Enggak Ada Lawan Pakai Motor Baru Yamaha Inceran'])[1]/preceding::a[2]</value>
      <webElementGuid>1d21fa76-4869-4744-b3ac-a56c24a56ad5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Agricultural Machinery']/parent::*</value>
      <webElementGuid>b1af1627-1b4f-4b2d-8965-6daa5f3ed291</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[9]</value>
      <webElementGuid>44595f69-fb91-4828-add5-0e8986030f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/a</value>
      <webElementGuid>7bc66839-f078-4aa3-933f-5bb920060d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'news-tab-tab-AGRI' and (text() = 'Agricultural Machinery' or . = 'Agricultural Machinery')]</value>
      <webElementGuid>c83464d3-227d-48e4-8bd8-9db704ff4254</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
