<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_Used Motorcycle</name>
   <tag></tag>
   <elementGuidId>ee0321ef-f979-43c9-972e-006cc5244076</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#news-tab-tab-UMC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='news-tab-tab-UMC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=tab[name=&quot;Used Motorcycle&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7f549517-59b3-44a5-a81e-1a38dd11b370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>520a9774-062f-41da-bea9-b18f224bde51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>397d7b16-0e4e-4a8a-9318-8a2b010d9489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rb-event-key</name>
      <type>Main</type>
      <value>UMC</value>
      <webElementGuid>d81463dc-3350-4027-b335-fde0d4c9b2e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>news-tab-tab-UMC</value>
      <webElementGuid>02c6e5ed-1a0e-4dd7-9c17-ae80624bc7da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>news-tab-tabpane-UMC</value>
      <webElementGuid>f189eff9-a58d-4f34-8f17-375430d2c611</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4fa5c6ee-e17c-4d98-a68a-0ef444f6c12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-promoTabs nav-link</value>
      <webElementGuid>d898efed-7395-40a7-a150-99e277287a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Used Motorcycle</value>
      <webElementGuid>0fe17629-8e2e-40a3-a8d4-d94a1df69313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;news-tab-tab-UMC&quot;)</value>
      <webElementGuid>9b6a7da1-becd-43f0-9297-77190a87cec1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='news-tab-tab-UMC']</value>
      <webElementGuid>9a972fe2-e9ea-42c9-8f2e-1ab6b6191b2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[2]/div/div/div[4]/a</value>
      <webElementGuid>86584b26-843d-43a8-87cf-10eafa6912d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Used Motorcycle')]</value>
      <webElementGuid>27cc3a61-92fc-4d05-86bc-2bfca20332e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EVENT &amp; PROMO'])[1]/following::a[4]</value>
      <webElementGuid>137d3aaf-4da0-4927-a62c-c15331d468c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BAF Mobile'])[1]/following::a[4]</value>
      <webElementGuid>586142cf-d4f1-4916-bc43-43f3ba6bae7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Motor Baru'])[1]/preceding::a[6]</value>
      <webElementGuid>eb8a0bb0-b3d1-4535-b84e-457be75fdaf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Emang Enggak Ada Lawan Pakai Motor Baru Yamaha Inceran'])[1]/preceding::a[6]</value>
      <webElementGuid>4145074f-5d56-4803-8230-ed178b8c2d27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Used Motorcycle']/parent::*</value>
      <webElementGuid>cb3f9615-dcf8-43d6-ab6b-dda3a4d9ff7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[5]</value>
      <webElementGuid>c4dceb00-f540-48c4-8b40-3d8469b50469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a</value>
      <webElementGuid>d965c5d6-86aa-40c9-8ed3-77d57e276bb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and @id = 'news-tab-tab-UMC' and (text() = 'Used Motorcycle' or . = 'Used Motorcycle')]</value>
      <webElementGuid>29030706-ffb7-4fc7-a86c-2d8872eec24b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
