<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Download 2</name>
   <tag></tag>
   <elementGuidId>c26f7f3a-d52c-4b86-a97c-158323891a08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body[1]/div[1]/main[1]/main[1]/div[2]/div[3]/nav[1]/div[3]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;\32 018&quot;] >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>01dcaf2f-617c-4531-b00e-4e2e645bbf72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>2018</value>
      <webElementGuid>9fda4a74-53b5-4d11-b2dd-ebe00a58086c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 p-3 my-3 cursor-pointer</value>
      <webElementGuid>e824a878-7e8e-49cf-ac85-b6f6af6880fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LAPORAN KEUANGAN 30 JUNI 2018 / FINANCIAL STATEMENT 30 JUNE 2018</value>
      <webElementGuid>0dddec21-d6a4-4d1b-a7fd-a3fcebfd3220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__className_4df22e&quot;]/main[@class=&quot;layout&quot;]/div[2]/div[3]/nav[@class=&quot;d-block px-0 navbar navbar-expand navbar-light&quot;]/div[@id=&quot;2018&quot;]</value>
      <webElementGuid>6efa7b45-d53f-4025-a03f-d1b5e999f66c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='2018'])[2]</value>
      <webElementGuid>7c65f2a7-4651-487f-9547-4bba1621d7cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[2]/div[3]/nav/div[3]</value>
      <webElementGuid>2939dd98-8af7-4a8a-bb1b-68c0d4aca6e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LAPORAN KEUANGAN 31 DESEMBER 2018 / FINANCIAL STATEMENT 31 DECEMBER 2018'])[1]/following::div[1]</value>
      <webElementGuid>4f6c8cf9-d606-4660-9cfc-9b3ac9fcfe2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FINANCIAL STATEMENTS'])[1]/following::div[10]</value>
      <webElementGuid>d0d150fc-72d4-4790-8d22-3455157d9e22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PT Bussan Auto Finance'])[1]/preceding::div[6]</value>
      <webElementGuid>e493b30e-386f-4a04-bec1-d30680bb47cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//nav/div[3]</value>
      <webElementGuid>9fb33d94-eaca-49f5-a0f4-0fd6381ccdad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = '2018' and (text() = 'LAPORAN KEUANGAN 30 JUNI 2018 / FINANCIAL STATEMENT 30 JUNE 2018' or . = 'LAPORAN KEUANGAN 30 JUNI 2018 / FINANCIAL STATEMENT 30 JUNE 2018')]</value>
      <webElementGuid>73292491-cdf8-4e3b-8f48-1a5043c6c5d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
