<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Youtube</name>
   <tag></tag>
   <elementGuidId>4e4d8f06-9b1d-4fa7-bd09-4b9a501a8acc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#widget2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='widget2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[title=&quot;BAF Company Profile 2022&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>23267de0-bd03-4183-aafe-9e14f0a36f0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3f5cace3-24c0-4475-913e-2fe00967754d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allow</name>
      <type>Main</type>
      <value>accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share</value>
      <webElementGuid>40a154b8-c79b-4c4a-b391-15acaeb92b3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>strict-origin-when-cross-origin</value>
      <webElementGuid>527a1072-c065-43ca-90c3-dcd5340f48d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>BAF Company Profile 2022</value>
      <webElementGuid>3e8200e6-c098-408a-a6ce-7a23eb734d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>e48de83f-c4c9-4760-b347-3bba318d4c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>e33abc4d-7dab-42c7-ae13-71bc7c3c1099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://www.youtube.com/embed/_0-hV5gwpwU?autoplay=0&amp;mute=0&amp;controls=0&amp;origin=https%3A%2F%2Fwww.baf.id&amp;playsinline=1&amp;showinfo=0&amp;rel=0&amp;iv_load_policy=3&amp;modestbranding=1&amp;enablejsapi=1&amp;widgetid=1</value>
      <webElementGuid>ea52239f-63b0-4da1-8d47-709071371fad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>widget2</value>
      <webElementGuid>e45e4d58-1f88-4920-bed7-7335bde40634</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-gtm-yt-inspected-11</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7fc0525d-ea84-4259-8b09-24819dda9bb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;widget2&quot;)</value>
      <webElementGuid>e7cf5284-b15e-4bc6-999f-a79ef872d59f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='widget2']</value>
      <webElementGuid>7f778d82-cfde-4e8f-9523-84fa5efeb9e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='company-profile']/div/div/div[2]/div/div/div/iframe</value>
      <webElementGuid>8867993e-1ce1-43d4-b7a3-7a8fb8404223</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>12325cb9-9ded-4e87-86aa-b25cd08ee1f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@title = 'BAF Company Profile 2022' and @src = 'https://www.youtube.com/embed/_0-hV5gwpwU?autoplay=0&amp;mute=0&amp;controls=0&amp;origin=https%3A%2F%2Fwww.baf.id&amp;playsinline=1&amp;showinfo=0&amp;rel=0&amp;iv_load_policy=3&amp;modestbranding=1&amp;enablejsapi=1&amp;widgetid=1' and @id = 'widget2']</value>
      <webElementGuid>397bd79d-280b-4ea8-b871-480cc3471e96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
