<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Banner 2</name>
   <tag></tag>
   <elementGuidId>cee11b86-a97a-4db9-a047-60ee5437dfdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/main/div[2]/div/div/div[5]/img</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@alt = 'flashdeal12']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>main.__className_4df22e:nth-child(1) main.layout div:nth-child(3) div.carousel.slide div.carousel-inner div.active.carousel-item:nth-child(2) > img.d-block.w-100</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=img[name=&quot;suku bunga desember&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>753df637-2a5a-4221-94b6-2062c4b05389</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>d-block w-100</value>
      <webElementGuid>db4d9ba1-c7bf-4353-b927-c0092a5142fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://baf-mobile-prod.oss-ap-southeast-5.aliyuncs.com/bannerweb%2F1734427749909.jpeg?Expires=1735057806&amp;OSSAccessKeyId=LTAI5tFAFQkoFApg3bDqxLsA&amp;Signature=7MQtxq23mwhTdgm62RGkXHiMp8U%3D</value>
      <webElementGuid>2e3d606c-bb5e-451a-8e37-8ee7c50a928b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>flashdeal12</value>
      <webElementGuid>7b4c906b-c84b-40a3-8152-4673bd8226a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__className_4df22e&quot;]/main[@class=&quot;layout&quot;]/div[2]/div[@class=&quot;carousel slide&quot;]/div[@class=&quot;carousel-inner&quot;]/div[@class=&quot;active carousel-item&quot;]/img[@class=&quot;d-block w-100&quot;]</value>
      <webElementGuid>85b58b7c-82b2-4fcb-a136-e037589f389c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[2]/div/div/div[5]/img</value>
      <webElementGuid>7a5d1f30-55d7-49d2-b59f-351ab5e97ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='suku bunga desember']</value>
      <webElementGuid>ee6166c8-80bd-413f-8068-d47e5044a749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/img</value>
      <webElementGuid>89806f1e-ff78-4363-ac81-db34bdcb9962</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://baf-mobile-prod.oss-ap-southeast-5.aliyuncs.com/bannerweb%2F1734428594399.jpeg?Expires=1735052461&amp;OSSAccessKeyId=LTAI5tFAFQkoFApg3bDqxLsA&amp;Signature=dxvsVVvM4whqeFUo7cNfGs%2FUEOo%3D' and @alt = 'suku bunga desember']</value>
      <webElementGuid>fbb73cfb-625e-4ea4-9aaf-dc65aeec8b37</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
