<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Top Brand</name>
   <tag></tag>
   <elementGuidId>4d67dc63-0b63-4711-8d1f-edba28680c1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__next']/main/main/div[3]/div/div/img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.card-img.ml-1.mr-1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.float-right > img:nth-child(2)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8fde6e2c-d292-4c97-b19a-dba93bf7be99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>card-img ml-1 mr-1</value>
      <webElementGuid>498a2d3d-5ffa-4ac6-9c2b-f063ed2451b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/images/image/footer/top-brand.webp</value>
      <webElementGuid>311bd37b-b983-4ff9-b7e7-c1194eb68942</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__className_4df22e&quot;]/main[@class=&quot;layout&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;border-bottom-0 bg-white card-header&quot;]/div[@class=&quot;float-right&quot;]/img[@class=&quot;card-img ml-1 mr-1&quot;]</value>
      <webElementGuid>f71b7947-4a82-475f-9f07-c0399defa90a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[3]/div/div/img[2]</value>
      <webElementGuid>e5f4bd39-c709-44e1-b9c3-4195c23345a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/img[2]</value>
      <webElementGuid>05edbae6-6c54-40dc-afd7-70fe7eef9925</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/images/image/footer/top-brand.webp']</value>
      <webElementGuid>5c7a30d6-5d18-46fe-97b9-5764e4b14413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
