<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>nav_Tab Product</name>
   <tag></tag>
   <elementGuidId>901266f5-171f-4c70-8df7-5cc1e87d117c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='__next']/main[1]/main[1]/section[1]/div[1]/div[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.col</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[id=&quot;__next&quot;] div >> internal:has-text=&quot;Choose a MotorcyclePlease selectChoose VariantPlease selectChoose CityPlease sel&quot;i >> nth=2</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a7e9c291-2dfd-446f-961d-30b6517212a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col</value>
      <webElementGuid>d8811d39-d332-4ab2-9b98-6b574e7709c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Choose a MotorcyclePlease selectChoose VariantPlease selectChoose CityPlease selectMotorcycle PriceTime PeriodPlease selectDown PaymentPlease selectCalculate Your Installment</value>
      <webElementGuid>5280bb6c-c214-4508-8f0f-4086f18b19ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__next&quot;)/main[@class=&quot;__className_4df22e&quot;]/main[@class=&quot;layout&quot;]/div[@class=&quot;section-container container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col&quot;]</value>
      <webElementGuid>7762081e-5893-4825-9d20-6bf5457f97d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/main/main/div[5]/div/div</value>
      <webElementGuid>aac74e62-5e43-413d-b778-59539e2d8296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[9]/following::div[32]</value>
      <webElementGuid>acd02649-06cf-4f20-aa4b-550369c17e28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Harbolnas Mantap Pol Promonya dengan #CicilAjadiBAF!'])[3]/following::div[32]</value>
      <webElementGuid>037283f9-73b8-4708-91b7-3783a01163ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div</value>
      <webElementGuid>88209ca3-a513-4c93-a010-a07aa7ea828c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Choose a MotorcyclePlease selectChoose VariantPlease selectChoose CityPlease selectMotorcycle PriceTime PeriodPlease selectDown PaymentPlease selectCalculate Your Installment' or . = 'Choose a MotorcyclePlease selectChoose VariantPlease selectChoose CityPlease selectMotorcycle PriceTime PeriodPlease selectDown PaymentPlease selectCalculate Your Installment')]</value>
      <webElementGuid>2474f2f2-2b61-431c-a110-c2aa8bd109db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
